import { execSync, spawn } from 'node:child_process'
import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { setTimeout as sleep } from 'node:timers/promises'
import { chromium } from 'playwright-core'

const ROOT = process.cwd()
const OUT = path.join(ROOT, 'tmp', 'verify')

const scenarios = [
  { name: 'personal-dotnet-full', siteType: 'personal', backend: 'dotnet', template: 'midnight', language: 'en', modules: ['pages', 'contact-form', 'auth'], ui: ['anim.reveal', 'anim.text-reveal', 'anim.magnetic'] },
  { name: 'personal-django-min', siteType: 'personal', backend: 'django', template: 'paper', language: 'fa', modules: ['pages'], ui: ['anim.reveal'] },
  { name: 'business-django-full', siteType: 'business', backend: 'django', template: 'ocean', language: 'en', modules: ['pages', 'contact-form'], ui: ['anim.tilt', 'anim.marquee'] },
  { name: 'business-dotnet-min', siteType: 'business', backend: 'dotnet', template: 'mono', language: 'en', modules: ['pages'], ui: [] },
  { name: 'shop-django-full', siteType: 'shop', backend: 'django', template: 'forest', language: 'fa', modules: ['pages', 'contact-form', 'auth', 'shop-catalog'], ui: ['anim.reveal', 'anim.hover-lift'] },
  { name: 'shop-dotnet-noauth', siteType: 'shop', backend: 'dotnet', template: 'sunset', language: 'en', modules: ['pages', 'contact-form', 'shop-catalog'], ui: ['anim.aurora'] }
]

function routesFor(s) {
  const routes = ['/', '/about']
  if (s.siteType === 'personal') routes.push('/portfolio')
  if (s.siteType === 'business') routes.push('/services')
  if (s.modules.includes('contact-form')) routes.push('/contact')
  if (s.modules.includes('shop-catalog')) routes.push('/products', '/cart')
  if (s.modules.includes('auth')) routes.push('/login', '/dashboard', '/admin')
  return routes
}

function run(cmd, opts = {}) {
  execSync(cmd, { stdio: 'pipe', shell: true, ...opts })
}

async function main() {
  mkdirSync(OUT, { recursive: true })
  const results = []

  for (let i = 0; i < scenarios.length; i++) {
    const s = scenarios[i]
    let dest = path.join(OUT, s.name)
    console.log(`\n=== [${i + 1}/${scenarios.length}] ${s.name} ===`)

    try {
      rmSync(dest, { recursive: true, force: true, maxRetries: 5, retryDelay: 300 })
    } catch {
      dest = `${dest}-${Date.now()}`
      console.log(`  (previous dir locked, using ${path.basename(dest)})`)
    }
    const blueprintPath = path.join(OUT, `${s.name}.blueprint.json`)
    writeFileSync(blueprintPath, JSON.stringify({
      projectName: s.name,
      siteType: s.siteType,
      backend: s.backend,
      database: 'sqlite',
      template: s.template,
      language: s.language,
      bilingual: s.language === 'fa',
      modules: s.modules,
      uiModules: s.ui,
      branding: {
        title: `${s.siteType[0].toUpperCase()}${s.siteType.slice(1)} Test`,
        tagline: 'Generated by the SiteForge verification harness.',
        ...(s.language === 'fa'
          ? { titleFa: 'سایت نمونه', taglineFa: 'ساخته شده توسط ابزار اعتبارسنجی سایتفورج' }
          : {}),
        logo: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',
        logoMode: 'both'
      }
    }, null, 2))
    run(`npx tsx packages/generator/src/cli.ts --blueprint "${blueprintPath}" --out "${dest}"`, { cwd: ROOT })

    const frontDir = path.join(dest, 'frontend')
    run('npm install --no-fund --no-audit', { cwd: frontDir })
    run('npx vite build', { cwd: frontDir })

    const port = 4400 + i
    const preview = spawn('npx.cmd', ['vite', 'preview', '--port', String(port), '--strictPort'], {
      cwd: frontDir,
      stdio: 'ignore',
      shell: true
    })

    try {
      let up = false
      for (let attempt = 0; attempt < 30; attempt++) {
        await sleep(500)
        try {
          const res = await fetch(`http://localhost:${port}/`)
          if (res.ok) { up = true; break }
        } catch {}
      }
      if (!up) throw new Error('preview server did not start')

      const browser = await chromium.launch({ channel: 'msedge', headless: true })
      const page = await browser.newPage()
      const pageErrors = []
      page.on('pageerror', err => pageErrors.push(String(err)))

      for (const route of routesFor(s)) {
        pageErrors.length = 0
        await page.goto(`http://localhost:${port}${route}`, { waitUntil: 'networkidle' })
        await sleep(700)
        const rootChildren = await page.evaluate(() => document.getElementById('root')?.children.length ?? 0)
        const bodyTextLen = await page.evaluate(() => document.body.innerText.trim().length)
        const status = pageErrors.length === 0 && rootChildren > 0 && bodyTextLen > 20 ? 'PASS' : 'FAIL'
        results.push({ scenario: s.name, route, status, errors: [...pageErrors], rootChildren, bodyTextLen })
        console.log(`  ${status} ${route} (root=${rootChildren}, text=${bodyTextLen})${pageErrors.length ? ` ERRORS: ${pageErrors.join(' | ').slice(0, 300)}` : ''}`)
      }

      await browser.close()
    } finally {
      try {
        spawn('taskkill', ['/F', '/PID', String(preview.pid), '/T'], { stdio: 'ignore', shell: true })
      } catch {}
    }
  }

  console.log('\n===== SUMMARY =====')
  const failed = results.filter(r => r.status === 'FAIL')
  console.log(`${results.length - failed.length}/${results.length} checks passed`)
  for (const f of failed) {
    console.log(`FAIL ${f.scenario} ${f.route}: errors=${f.errors.join(' | ') || 'none'} rootChildren=${f.rootChildren} text=${f.bodyTextLen}`)
  }
  process.exit(failed.length > 0 ? 1 : 0)
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
