# Generated by Django 5.2.17 on 2026-08-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_fa', models.CharField(blank=True, default='', max_length=120)),
                ('summary', models.CharField(blank=True, default='', max_length=240)),
                ('summary_fa', models.CharField(blank=True, default='', max_length=240)),
                ('description', models.TextField(blank=True, default='')),
                ('description_fa', models.TextField(blank=True, default='')),
                ('tags', models.TextField(default='[]')),
                ('gallery', models.TextField(default='[]')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
