# Generated by Django 5.2.17 on 2026-08-28 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('sandbox', models.BooleanField(default=True)),
                ('merchant_id', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_fa', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('description_fa', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('image_url', models.URLField(blank=True)),
                ('gallery', models.TextField(default='[]')),
                ('details', models.TextField(default='{}')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('failed', 'failed'), ('canceled', 'canceled')], default='pending', max_length=12)),
                ('authority', models.CharField(blank=True, default='', max_length=64)),
                ('ref_id', models.CharField(blank=True, default='', max_length=64)),
                ('items_snapshot', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'open'), ('answered', 'answered'), ('closed', 'closed')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], max_length=8)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shop.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
